version: '3'
services:
  # just doing this for now, will need to change later perhaps use a start.sh script
  proto:
    build: ./proto
    volumes:
      - ./proto:/proto
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  db-service:
    build: ./database-service
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres