version: '3'
services:
  # just doing this for now, will need to change later perhaps use a start.sh script
  proto:
    build: ./proto
    volumes:
      - ./proto:/proto
  db:
    build: ./database-service
    ports:
      - "5432:5432"